[package]
name = "yet-another-bg3-mod-loader"
version = "0.2.2"
edition = "2021"

[dependencies]
serde = { version = "1.0.196", features = ["derive"] }
toml = "0.8.10"
serde_json = "1.0.113"
directories = "5.0.1"
human-panic = "1.2.3"
eyre = "0.6.12"
backtrace = "0.3.69"
bg3-plugin-lib = { git = "https://github.com/MolotovCherry/BG3-Plugin-Lib" }
tray-icon = "0.11.3"
winit = "0.29.10"
unicase = "2.7.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing-appender = "0.2.3"
clap = { version = "4.5.1", features = ["derive"] }

[dependencies.windows]
version = "0.52.0"
features = [
    "Win32_Foundation",
    "Win32_System_ApplicationInstallationAndServicing",

    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Threading",
    "Win32_System_Memory",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_LibraryLoader",
    "Win32_Storage_FileSystem",

    "Win32_Security",

    "Win32_System_ProcessStatus",

    "Win32_System_Console",
]

[build-dependencies]
winres = "0.1.12"

# so we can get stacktraces in release
[profile.release]
debug = true

[profile.release-debug]
inherits = "release"
debug-assertions = true
