[package]
name = "yet-another-bg3-mod-loader"
version = "0.2.0"
edition = "2021"

[dependencies]
log = "0.4.20"
simplelog = "0.12.1"
serde = { version = "1.0.193", features = ["derive"] }
toml = "0.8.8"
serde_json = "1.0.108"
directories = "5.0.1"
human-panic = "1.2.2"
anyhow = "1.0.75"
backtrace = "0.3.69"
chrono = "0.4.31"
bg3-plugin-lib = { git = "https://github.com/MolotovCherry/BG3-Plugin-Lib" }
tray-icon = "0.11.1"
winit = "0.29.4"

[dependencies.windows]
version = "0.52.0"
features = [
    "Win32_Foundation",
    "Win32_System_ApplicationInstallationAndServicing",

    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Threading",
    "Win32_System_Memory",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_LibraryLoader",

    "Win32_Security",

    "Win32_System_ProcessStatus",
]

[build-dependencies]
winres = "0.1.12"

# so we can get stacktraces in release
[profile.release]
debug = true

[profile.release-debug]
inherits = "release"
debug-assertions = true
