[workspace]
resolver = "2"
members = ["crates/dll-loader", "crates/yet-another-bg3-mod-loader"]

[profile.dev]
opt-level = 1

[profile.dev-dbg]
inherits = "dev"
opt-level = 0

[profile.release]
lto = true
strip = true
codegen-units = 1

[profile.release-dbg]
inherits = "release"
debug = true
strip = false
debug-assertions = true
