[package]
name = "yet-another-bg3-mod-loader"
version = "0.1.2"
edition = "2021"

[dependencies]
log = "0.4.20"
simplelog = "0.12.1"
serde = { version = "1.0.193", features = ["derive"] }
toml = "0.8.8"
serde_json = "1.0.108"
directories = "5.0.1"
human-panic = "1.2.2"
anyhow = "1.0.75"
backtrace = "0.3.69"
chrono = "0.4.31"
winreg = "0.52.0"
sysinfo = "0.29.10"
bg3-plugin-lib = { git = "https://github.com/MolotovCherry/BG3-Plugin-Lib" }

[dependencies.windows]
version = "0.52.0"
features = [
    "Win32_Foundation",
    "Win32_System_ApplicationInstallationAndServicing",

    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Threading",
    "Win32_System_Memory",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_LibraryLoader",

    "Win32_Security",
]

[dependencies.windows-sys]
version = "0.52.0"
features = ["Win32_System_LibraryLoader", "Win32_Foundation"]

[build-dependencies]
winres = "0.1.12"
