[package]
name = "yet-another-bg3-mod-loader"
version = "0.2.4"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
toml = "0.8.11"
serde_json = "1.0.114"
directories = "5.0.1"
human-panic = "1.2.3"
eyre = "0.6.12"
backtrace = "0.3.69"
native-plugin-lib = { git = "https://github.com/MolotovCherry/Native-Plugin-Lib" }
tray-icon = "0.12.0"
winit = "0.29.14"
unicase = "2.7.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing-appender = "0.2.3"
clap = { version = "4.5.3", features = ["derive"] }

[dependencies.windows]
version = "0.54.0"
features = [
    "Win32_Foundation",
    "Win32_System_ApplicationInstallationAndServicing",

    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Threading",
    "Win32_System_Memory",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_LibraryLoader",
    "Win32_Storage_FileSystem",

    "Win32_Security",

    "Win32_System_ProcessStatus",

    "Win32_System_Console",
]

[build-dependencies]
winres = "0.1.12"
