[package]
name = "shared"
version = "0.1.0"
edition = "2021"
rust-version = "1.82"

[dependencies]
eyre.workspace = true
tracing.workspace = true
windows.workspace = true
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
directories = "5.0.1"
backtrace = "0.3.74"
toml = "0.8.19"
tokio = { version = "1.41.1", features = ["net", "rt"] }
