[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "5.0.1"
eyre.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json = "1.0.128"
backtrace = "0.3.74"
toml = "0.8.19"
tokio = { version = "1.40.0", features = ["net", "rt"] }
